### ISSUE TITLE
Hardcoded values

### ISSUE THREAD

**Issue by tenderitaf** [Talos-crypto/Talos-Android#1]
Hi,
I would like to congratulate you first for th fantastic job you guys did.

Here are some issue I faced ;

in avaapp google client id for the server is hardcoded.
selfsigned certificate for your ec2 instance is embedded in the app :) 
dataset fro ava don't exist causing app to crash when sync with backend.

Regards

**Comment by lubux** [comment]
Hey, thanks for your interest in our work and sharing your problems. 
Yes, you are right you have to set up your own google client id for the server and server certificate.

> dataset fro ava don't exist causing app to crash when sync with backend.

Unfortunately, we are not allowed to share the dataset publicly.
If you any further problems or questions, don't hesitate to contact me.
